### ISSUE TITLE
Cpp or C code doesnt compile

### ISSUE THREAD

**Issue by AvaterClasher** [iojcde/owo#1]
```c
#include <stdio.h>

int main() {
    printf("Hello");
}
```
The code sample given in the readme examples doesn't compile.

> Untarring /sysroot.tar... done.
> Fetching and compiling /clang.wasm... done.
> clang -cc1 -Wall -emit-obj -disable-free -isysroot / -internal-isystem /include/c++/v1 -internal-isystem /include -internal-isystem /lib/clang/8.0.1/include -ferror-limit 19 -fmessage-length 80 -fcolor-diagnostics -O2 -o program.o -x c++ program.cpp
program.cpp:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
Exit code: 1 (process exited with code 1.)

How to solve this. Btw awesome work !!

**Comment by iojcde** [comment]
Should be fixed now.
